version: '3.7'
services:
  py-test-bot:
    container_name: test213
    build: .
    command: python3.10 app.py
    env_file:
      - .env
    restart: always
    ports:
      - "8443:3001"
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge